language: python
env:
  global:
    - DEPENDS="gfortran-4.9 binutils"
python:
    - "3.4"
before_install:
  - sudo apt-get install gfortran g77
install: 
    - pip install -r requirements.txt
script:
    - python setup.py unittests
